image:https://gitlab.com/e257/testing/dirsuite/badges/master/build.svg["Build status", link="https://gitlab.com/e257/testing/dirsuite/-/jobs/"]
image:https://gitlab.com/e257/testing/dirsuite/badges/master/coverage.svg["Coverage", link="https://gitlab.com/e257/testing/dirsuite/-/jobs/"]
image:https://maven-badges.herokuapp.com/maven-central/fi.e257.testing/dirsuite_2.13/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/fi.e257.testing/dirsuite_2.13"]
image:https://javadoc.io/badge/fi.e257.testing/dirsuite_2.13.svg?color=blue["javadoc", link="https://javadoc.io/page/fi.e257.testing/dirsuite_2.13/latest/fi/e257/testing/dirsuite/index.html"]

= DirSuite test framework and add-on for ScalaTest


This is DirSuite add-on to ScalaTest. DirSuite can run (huge) collection of tests which are defined on filesystem.
Arguments, inputs and expected reference output files are defined in the test directory.


== Documentation

 * link:./docs/dirsuite.adoc[DirSuite Reference] contains reference information for dirsuite
 * link:./docs/howto.adoc[DirSuite HOWTO] has examples how to use dirsuite
 * Example DirSuite test setup:
 ** link:./examples/[examples] Demo setup with example test corpus.
 ** link:./examples/src/test/scala/DirSuiteDemo.scala[examples -> src -> tests -> DirSuiteDemo] DirSuite tests against example corpus.
 ** link:./examples/tests/[examples -> tests] Test corpus for example project
 * link:https://gitlab.com/e257/accounting/tackler[Tackler Project] has extensive set of tests based on DirSuite
 ** link:https://gitlab.com/e257/accounting/tackler/tree/master/tests[Tackler's DirSuite tests]
 ** link:https://gitlab.com/e257/accounting/tackler/blob/master/project/TacklerTests.scala[Tackler's clean up setup for DirSuite tests]


== Releases

Dependency settings for SBT are:

    libraryDependencies += "fi.e257.testing" %% "dirsuite" % "version-number"

DirSuite artifacts are released on Maven Central Repository.

For release information and version history details, see link:./CHANGELOG.adoc[CHANGELOG]. For Upgrade instructions,
see link:./UPGRADE.adoc[UPGRADE].


== Contributing to DirSuite

Contributions to the project are welcome. See
link:./CONTRIBUTING.adoc[CONTRIBUTING] how you could help.

Your pull requests and patches can be merged only if you can certify
the link:./DCO[Developer Certificate of Origin (DCO), Version 1.1].

By signing-off your commit you certify DCO and acknowlegde that you have
the rights to submit your pull requsted or patch as an open-source contribution,
as stated in link:./DCO[Developer Certificate of Origin].

Certifying DCO is done by adding a `Signed-off-by` line
to **every** git commit message:

    Signed-off-by: gitlab-account <your.real@email.address>

If you set your `user.name` and `user.email` correctly in git config,
then git will automatically include that line for you with `git commit -s`.
You can also create a git `commit.template` with appropriate content. These
settings can be done per repository basis,  so they don't have to be globally
set in your system.

Please make sure that you sign-off all your PR's commits.


== Credits

Without link:http://www.scalatest.org/[ScalaTest] this project 
would not exists. See link:./THANKS.adoc[THANKS] for full list of credits.


== License

....
Copyright 2016-2019 E257.FI Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
....

